site_name: Florence Player
markdown_extensions:
  - footnotes
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - meta
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/florence_logo.png
  font:
    text: Noto Sans
extra_css:
  - css/extra.css
repo_url: https://github.com/uq-flor-pro/florence-player
repo_name: florence-player
extra:
  homepage: https://itee.uq.edu.au/florence
edit_uri: ""
